### ISSUE TITLE
Websocket calls are not being matched by any @MessageMapping in Spring 

### ISSUE THREAD

**Issue by funder7** [kiegroup/optaweb-vehicle-routing#314] opened 2020-05-27 21:22 UTC
Hello, 

I don't know if it's a good practice, but I've imported all the classes of _optaweb-backend_ inside my project, built with jhipster. And now I'd like to test if everything works by using the optaweb-client. 

Even if my backend code was configured exactly the same as optaweb-backend, I had some problems with incoming Websocket messages.
One of them was due to CORS, not accepting the "*" wildcard, fixed by specifying the client hostname "localhost:3000".  Then the client was able to send the handshake correctly. 

The problem I'm facing now is that the optaweb-client application is sending the subscription message, but apparently there's no match in the Spring Controller.
This is from the logs:

```
2020-05-27 21:47:16.090 DEBUG 2761 --- [boundChannel-19] .WebSocketAnnotationMethodMessageHandler : Searching methods to handle SUBSCRIBE /app/topic/route id=sub-1590608836085-631 session=fyprt1oy, lookupDestination='/topic/route'
2020-05-27 21:47:16.090 DEBUG 2761 --- [boundChannel-19] .WebSocketAnnotationMethodMessageHandler : No matching message handler methods.
```

I'm opening this issue because I see that there are many comments near Websocket setup code,  both in optaweb backend and frontend modules. That made me think of a "work in progress" situation. So I tought that it was a good idea to ask the author :-)

 I’m referring to this section in particular:

### org.optaweb.vehiclerouting.plugin.websocket.WebSocketConfig

```java
@Configuration
@EnableWebSocketMessageBroker
class WebSocketConfig implements WebSocketMessageBrokerConfigurer {

    @Override
    public void configureMessageBroker(MessageBrokerRegistry registry) {
        // STOMP messages whose destination header begins with /app are routed to @MessageMapping methods
        // in @Controller classes.
        // Not sure if "/topic" should be an application prefix but I couldn't get @SubscribeMapping("/route") working
        // without this.
        registry.setApplicationDestinationPrefixes("/app", "/topic");
        // Use the built-in message broker for subscriptions and broadcasting,
        // and route messages whose destination header begins with /topic to the broker.
        registry.enableSimpleBroker("/topic");
    }

   // ....
}
```
###  Client - Server messaging 
 By setting websocket logging to debug, I can see the configured message endpoints printed at boot time:
```
	it.****.****.web.websocket.WebsocketController:
	{[MESSAGE],[/clear]}: clear()
	{[MESSAGE],[/location/{id}/delete]}: removeLocation(long)
	{[MESSAGE],[/vehicle/{id}/delete]}: removeVehicle(long)
	{[MESSAGE],[/location]}: addLocation(PortableLocation)
	{[MESSAGE],[/vehicle]}: addVehicle()
	{[MESSAGE],[/vehicle/{id}/capacity]}: changeCapacity(long,int)
	{[MESSAGE],[/vehicle/deleteAny]}: removeAnyVehicle()
	{[SUBSCRIBE],[/serverInfo]}: subscribeToServerInfoTopic()
	{[SUBSCRIBE],[/route]}: subscribeToRouteTopic()
	{[MESSAGE],[/demo/{name}]}: demo(String)
```

The client application is sending this message (without escape codes):

```
[" SUBSCRIBE
   id: sub-1590608836084-262
   destination: /app/topic/serverInfo "]
```

Please, check the request headers:
```
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: ###########
Sec-WebSocket-Version: 13
Upgrade: websocket
```

It seems that the ```Sec-WebSocket-Protocol``` key is missing, by reading this [paragraph](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#websocket-intro) in the official Spring docs.

As you can see from my logs, the controller endpoints are not prefixed by "/topic" or "/app" in the controller, so  why it works in the original project, and not in mine?!

### Project dependencies
To give you the last informations, some dependencies in my project:

**Spring**
- spring-boot: 2.2.7.RELEASE
- spring-core: 5.2.6.RELEASE
- spring-security-core: 5.2.4.RELEASE
- spring-security-messaging: 5.2.4.RELEASE
- spring-boot-starter-websocket: 2.2.7.RELEASE
- spring-websocket: 5.2.6.RELEASE
- spring-messaging: 5.2.6.RELEASE

**Optaplanner**
- optaplanner-spring-boot-starter: 7.37.0.Final:compile
- optaplanner-spring-boot-autoconfigure: 7.37.0.Final
- optaplanner-core: 7.37.0.Final

### Conclusion
If the post is too long, I apologize for that, and form my english too!
I'd like to specify that i'm not seeking for help (although any advices are welcome!), my intent is just to share my experience, in order to reply to the comments found in the code. 
It's important for me to understand if the problem I'm facing can be related to my dependencies versions, a fault with the project configuration, or whatever. 

Just a personal note... I'm happy to have found this project, I always wanted to work with something related to finding the best route. It's just now that I've found informations about the VR Problem, I wasn't aware of its notoriety.
However I wanted to send a thank you to the project creators, I hope with time to learn to use this library well, and why not, also make a contribution in the future if there will be the occasion.

Thanks for reading! ;-)
Federico

**Comment by f-ricchiuto** [comment] 2020-05-29 22:47
In the meanwhile I've fixed the problem, it was in the optaweb-client application, I can share it if it's useful

**Comment by yurloc** [comment] 2020-06-01 10:50
Federico, sorry for the late reply, I missed the notification about a new issue.

Thanks a lot for such a detailed report. I'm glad to hear that you have found a solution! I'm curious what was the cause of the issue. Especially if it's a bug in the upstream code, I would appreciate your help to fix it.

**Comment by f-ricchiuto** [comment] 2020-06-03 20:28
Hello @yurloc, no problem! I tought the message was too long, and nobody wanted to read it :-)
Sure I would be glad to share the solution: apparently it was just a misalignment of client/server endpoints. I don't exclude that this newer version of spring I'm using, configures STOMP endpoints in a different way, it could be.

I never collaborated with a project on github, how can I help? 
I suppose that fixing the problem on the current version would break it, it must be done on a new branch where the backend has the same dependencies versions as mine project.

**Comment by yurloc** [comment] 2020-06-04 20:48
OK, so if I understand correctly, the WebSocket code broke after moving to your JHipster project, and `optaweb-vehicle-routing` is not really affected by the issue. Can you confirm that? If it is the case, there is nothing to fix here.

If you think the issue is present in `optaweb-vehicle-routing`, we need to reproduce it here first. I've tried upgrading to the same versions of Spring dependencies as you have provided and didn't see any issue.

**Comment by yurloc** [comment] 2020-06-30 14:44
Closing. Without a reproducer there is nothing to fix upstream.

But thank you for the detailed report! It maybe useful for someone in the future.

**Closed by yurloc** 2020-06-30 14:44 UTC
